### ISSUE TITLE
No need to pass `nonce` to `execute`

### ISSUE THREAD

**Issue by martriay** [argentlabs/argent-contracts-starknet#3]
Jus as [there is no need to pass `this`](https://github.com/OpenZeppelin/cairo-contracts/issues/10), `nonce` can also be omitted from `execute` arguments, since [the contract already knows what's the only valid `nonce`](https://github.com/OpenZeppelin/cairo-contracts/commit/2c2e1bb745985c600643d0498682ab2498b64b89#diff-d223c9adb70603fcfe336e89fb620a6971d5ddf101a181e9c06ab077d2821e7aR174). Maybe this changes in the future if Cairo implements revert messages, then we could do something like:

```
assert nonce = current_nonce, "Invalid nonce"
```

until that, there is no reason to have a `nonce` parameter.

**Comment by juniset** [comment]
I think that makes sense if there is only one valid nonce such as the currently implemented incremental nonce. But there are other possible nonce patterns so I think that if we want to be general with the `execute` method and make it part of a standard interface for accounts then we should not make any assumption about the nonce.

**Comment by frangio** [comment]
@juniset Do you have examples of possible nonce patterns that would need it to be included?

**Comment by juniset** [comment]
@frangio you can have a nonce where the only requirement is that the nonce of a transaction must be greater than the previous one but not necessarily by 1. Or you can have a nonce whose requirement is that the transaction parameters, as computed by the `message_hash`, are unique and each executed `message_hash` is stored in a mapping.

We use these 2 different nonce strategies in the Argent wallet contract on L1.
