### ISSUE TITLE
cairo-lang 0.8.1 support

### ISSUE THREAD

**Issue by lsbyerley** [argentlabs/argent-contracts-starknet#35]
Seeing some module import errors in `./test/argent_account.py` on cairo-lang 0.8.1

https://github.com/argentlabs/argent-contracts-starknet/blob/develop/test/argent_account.py

`ImportError: cannot import name 'BlockInfo' from 'starkware.starknet.business_logic.state'`

**Comment by juniset** [comment]
Thanks! I believe with 0.8.1 `BlockInfo` has been moved to `starkware.starknet.business_logic.state.state`.

**Comment by juniset** [comment]
Should be fixed by #36 .

**Comment by juniset** [comment]
Closed by #36

**Comment by lsbyerley** [comment]
@juniset awesome thanks! i'll check it out soon
