### ISSUE TITLE
ArgentAccount does not allow execution simulation

### ISSUE THREAD

**Issue by FabijanC** [argentlabs/argent-contracts-starknet#62]
Same issue as reported here: https://github.com/OpenZeppelin/cairo-contracts/issues/471

To enable simulation and fee estimation, `QUERY_VERSION` (which is equal to `2**128 + TRANSACTION_VERSION`) should be allowed in this line, not just `TRANSACTION_VERSION`: https://github.com/argentlabs/argent-contracts-starknet/blob/a98731015b0f5be7071084da0459f95e0ef2ef43/contracts/account/library.cairo#L140

**Comment by juniset** [comment]
Thanks @FabijanC for flagging this. Can you have a look at #63 and approve if ok?
